### ISSUE TITLE
Dashing branch

### ISSUE THREAD

**Issue by ahcorde** [AcutronicRobotics/hans_modular_servomotor#2]
Can we create in this repo a `dashing` branch?

**Comment by ahcorde** [comment]
Done, do we need to include some ros2 dashing specific code? @YueErro

**Comment by YueErro** [comment]
AFAIK no, currently, this is an independent repo, it is not used in MARA. Anyhow i would change the branch to dashing in [mara-ros2.repos](https://github.com/AcutronicRobotics/MARA/blob/dashing/mara-ros2.repos#L17). Also, i would add to the TODO list make MARA compliant with this repo, same as we did with the robotiq gripper repo.
